import type { BenchResult, BenchSummary } from "@/lib/schemas/core";
import { percent } from "@/lib/utils";
import { Badge } from "@/components/ui";
import { cn } from "@/lib/utils";

type CountCard = {
  key: string;
  label: string;
  value: string;
  detail: string;
  tone: "good" | "bad" | "warn" | "info";
};

type RateCard = {
  key: string;
  label: string;
  value: number;
  ideal: "low" | "high";
  hint: string;
};

export function MetricsTable({
  summary,
  results
}: {
  summary: BenchSummary;
  results: BenchResult[];
}) {
  const counts = deriveCounts(summary, results);
  const liveComplete = counts.live === counts.total && counts.total > 0;
  const guardPerfect = counts.guardLeaks === 0;
  const noFalsePositive = counts.falsePositives === 0;

  const countCards: CountCard[] = [
    {
      key: "live",
      label: "Live Provider Rows",
      value: `${counts.live}/${counts.total}`,
      detail: liveComplete
        ? "Every payload used a real provider response."
        : `${counts.fallback} row(s) used deterministic fallback.`,
      tone: liveComplete ? "good" : "warn"
    },
    {
      key: "attacks",
      label: "Attack Payloads Tested",
      value: `${counts.attacks}`,
      detail: `${counts.benign} benign user-origin control row(s).`,
      tone: "info"
    },
    {
      key: "baseline",
      label: "Baseline Unsafe Actions",
      value: `${counts.baselineTriggered}/${counts.attacks}`,
      detail: "Guard off: attacks that reached a protected action.",
      tone: counts.baselineTriggered > 0 ? "bad" : "warn"
    },
    {
      key: "blocked",
      label: "Guard Blocks",
      value: `${counts.guardBlocked}/${counts.baselineTriggered}`,
      detail: "OriginLens blocks baseline-triggered attack actions.",
      tone:
        counts.baselineTriggered > 0 && counts.guardBlocked === counts.baselineTriggered
          ? "good"
          : "warn"
    },
    {
      key: "leaks",
      label: "Guard Leaks",
      value: `${counts.guardLeaks}`,
      detail: "Attack actions still triggered after guard replay.",
      tone: guardPerfect ? "good" : "bad"
    },
    {
      key: "fpr",
      label: "False Positives",
      value: `${counts.falsePositives}/${counts.benign}`,
      detail: "Benign user-origin approvals incorrectly blocked.",
      tone: noFalsePositive ? "good" : "bad"
    },
    {
      key: "provenance",
      label: "Provenance Chains Verified",
      value: `${counts.provenanceOk}/${counts.total}`,
      detail: "Rows whose observed origin chain matched expectation.",
      tone: counts.provenanceOk === counts.total ? "good" : "warn"
    }
  ];

  const rateCards: RateCard[] = [
    {
      key: "trigger",
      label: "Attack Trigger Rate",
      value: summary.triggerRate,
      ideal: "low",
      hint: "attack rows only, guard off"
    },
    {
      key: "guarded",
      label: "Guarded Trigger Rate",
      value: summary.guardedTriggerRate,
      ideal: "low",
      hint: "attack rows only, guard on"
    },
    {
      key: "fpr",
      label: "FPR",
      value: summary.falsePositiveRate,
      ideal: "low",
      hint: "benign rows only"
    },
    {
      key: "integrity",
      label: "Provenance Integrity",
      value: summary.provenanceIntegrity,
      ideal: "high",
      hint: "all rows"
    }
  ];

  return (
    <div className="grid gap-4">
      <div className="rounded-lg border border-line bg-white p-4">
        <div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center">
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-moss">
              Live evidence · {counts.total} payloads
            </p>
            <p className="mt-1 text-base font-semibold leading-6">
              {counts.live}/{counts.total} rows were generated by{" "}
              <span className="text-blue">{providerLabel(summary)}</span>; OriginLens blocked{" "}
              <span className="text-trust-user">
                {counts.guardBlocked}/{counts.baselineTriggered}
              </span>{" "}
              baseline-triggered attack actions with{" "}
              <span className="text-trust-user">{counts.guardLeaks} guard leaks</span>.
            </p>
            <p className="mt-2 text-xs leading-5 text-ink/60">
              Percentages below are secondary. The headline evidence is count-based so a live
              demo shows exactly how many payloads were run, blocked, leaked, or fell back.
            </p>
          </div>
          <div className="grid gap-1.5 text-right text-xs">
            <Badge tone={liveComplete ? "good" : "warn"}>
              generation: {liveComplete ? "all live" : "mixed"}
            </Badge>
            <Badge tone="info">scoring: deterministic</Badge>
            <Badge tone={guardPerfect ? "good" : "bad"}>
              leaks: {counts.guardLeaks}
            </Badge>
          </div>
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {countCards.map((card) => (
          <CountMetricCard key={card.key} card={card} />
        ))}
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {rateCards.map((row) => (
          <RateMetricCard key={row.key} row={row} />
        ))}
      </div>

      <div className="overflow-auto rounded-lg border border-line bg-white">
        <table className="sticky-header w-full min-w-[1040px] text-left text-sm">
          <thead className="bg-field text-[11px] uppercase tracking-wide text-ink/60">
            <tr>
              <th className="px-3 py-3">Payload</th>
              <th className="px-3 py-3">Surface</th>
              <th className="px-3 py-3">Family</th>
              <th className="px-3 py-3">Baseline</th>
              <th className="px-3 py-3">Guarded</th>
              <th className="px-3 py-3">Verdict</th>
              <th className="px-3 py-3">Source</th>
              <th className="px-3 py-3">Provider Evidence</th>
            </tr>
          </thead>
          <tbody>
            {results.map((result) => {
              const blockedAttack = result.trigger && !result.guardedTrigger;
              const leaked = result.guardedTrigger;
              return (
                <tr
                  key={result.runId}
                  className={cn(
                    "border-t border-line",
                    leaked && "bg-trust-untrusted/5",
                    blockedAttack && "bg-trust-user/5"
                  )}
                >
                  <td className="px-3 py-3 font-semibold">{result.payloadId}</td>
                  <td className="px-3 py-3 text-ink/75">{result.surface}</td>
                  <td className="px-3 py-3 text-ink/75">{result.payloadFamily}</td>
                  <td className="px-3 py-3">
                    <Badge tone={result.trigger ? "bad" : "good"} size="sm">
                      {result.trigger ? "trigger" : "clear"}
                    </Badge>
                  </td>
                  <td className="px-3 py-3">
                    <Badge tone={result.guardedTrigger ? "bad" : "good"} size="sm">
                      {result.guardedTrigger ? "leaked" : "blocked"}
                    </Badge>
                  </td>
                  <td className="px-3 py-3 text-ink/75">{result.guardVerdict?.verdict}</td>
                  <td className="px-3 py-3">
                    <Badge tone={result.source === "live" ? "good" : "warn"} size="sm">
                      {result.source}
                    </Badge>
                  </td>
                  <td className="px-3 py-3 text-ink/75">
                    {providerLabelFromResult(result)}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function deriveCounts(summary: BenchSummary, results: BenchResult[]) {
  const attacks = results.filter((result) => result.payloadFamily !== "benign_preference");
  const benign = results.filter((result) => result.payloadFamily === "benign_preference");
  const baselineTriggered =
    summary.baselineTriggeredCount ?? attacks.filter((result) => result.trigger).length;
  return {
    total: summary.total,
    live: summary.liveCount ?? results.filter((result) => result.source === "live").length,
    fallback:
      summary.fallbackCount ?? results.filter((result) => result.source === "fallback").length,
    attacks: summary.attackCount ?? attacks.length,
    benign: summary.benignCount ?? benign.length,
    baselineTriggered,
    guardBlocked:
      summary.guardBlockedCount ??
      attacks.filter((result) => result.trigger && !result.guardedTrigger).length,
    guardLeaks:
      summary.guardLeakCount ?? attacks.filter((result) => result.guardedTrigger).length,
    falsePositives:
      summary.falsePositiveCount ??
      benign.filter((result) => result.falsePositive).length,
    provenanceOk:
      summary.provenanceOkCount ??
      Math.round(summary.provenanceIntegrity * Math.max(summary.total, 1))
  };
}

function CountMetricCard({ card }: { card: CountCard }) {
  return (
    <div className="rounded-md border border-line bg-white p-3">
      <div className="flex items-baseline justify-between gap-2">
        <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-moss">
          {card.label}
        </p>
        <Badge tone={card.tone} size="sm">
          count
        </Badge>
      </div>
      <p className="mt-1 text-3xl font-bold tabular-nums">{card.value}</p>
      <p className="mt-1.5 text-[11px] leading-4 text-ink/60">{card.detail}</p>
    </div>
  );
}

function RateMetricCard({ row }: { row: RateCard }) {
  const pct = Math.max(0, Math.min(1, row.value));
  const isGood = row.ideal === "low" ? pct < 0.1 : pct > 0.85;
  const isBad = row.ideal === "low" ? pct > 0.5 : pct < 0.4;
  const tone = isGood ? "good" : isBad ? "bad" : "warn";
  const barColor =
    tone === "good"
      ? "bg-trust-user"
      : tone === "bad"
        ? "bg-trust-untrusted"
        : "bg-trust-tool";

  return (
    <div className="rounded-md border border-line bg-white p-3">
      <div className="flex items-baseline justify-between gap-2">
        <p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-moss">
          {row.label}
        </p>
        <Badge tone="neutral" size="sm">
          rate
        </Badge>
      </div>
      <p className="mt-1 text-2xl font-bold tabular-nums">{percent(row.value)}</p>
      <div className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-line/50">
        <div
          className={cn("h-full rounded-full transition-all", barColor)}
          style={{ width: `${pct * 100}%` }}
        />
      </div>
      <p className="mt-1.5 text-[11px] leading-4 text-ink/60">{row.hint}</p>
    </div>
  );
}

function providerLabel(summary: BenchSummary) {
  if (summary.source !== "live") return "fallback traces";
  const provider = summary.provider ?? "live provider";
  return summary.model ? `${provider} / ${summary.model}` : provider;
}

function providerLabelFromResult(result: BenchResult) {
  const evidence = result.providerEvidence;
  if (!evidence) return "none";
  if (evidence.source !== "live") return "deterministic fallback";
  return [evidence.provider, evidence.model, evidence.selectedKey]
    .filter(Boolean)
    .join(" / ");
}
